name: project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.6.0
  shared_preferences: ^2.2.0
  google_fonts: ^4.0.0
  bloc: ^8.1.2
  connectivity_plus: ^3.0.0
  flutter_bloc: ^8.1.3
  page_transition: ^2.0.9
  line_icons: ^2.0.3
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.5.0
  open_street_map_search_and_pick: 0.1.0
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  syncfusion_flutter_pdf: ^22.2.12
  path_provider: ^2.1.1
  open_file: ^3.3.2
  syncfusion_flutter_xlsio: ^22.2.12
  intl: 0.18.0
  flutter_native_splash: 2.2.16
  equatable: ^2.0.5
  fluttertoast: ^8.0.9
  permission_handler: 10.2.0
  device_info_plus: ^9.0.3
  camera: 0.10.3+2
  syncfusion_flutter_sliders: ^22.2.12
  url_launcher: ^6.1.14
  image: 4.0.17
  flutter_image_compress: ^2.1.0
  cool_alert: ^2.0.1
  sqflite: ^2.3.0
  device_preview: 1.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_map: 5.1.0
  latlong2: ^0.9.0

flutter_native_splash:
  color: "#FFFFFF"    # Set the background color of your splash screen
  image: "assets/images/pioneer_logo_new_v2.png"   # Set the image path for your splash screen
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
